SELECT 'start PMID index', CURRENT_DATE(), CURRENT_TIME();
CREATE INDEX PMID_IDX on bc2pubtator(PMID);
SELECT 'fin PMID index', CURRENT_DATE(), CURRENT_TIME();
CREATE INDEX TYPE_IDX on bc2pubtator(Type);
SELECT 'fin Type index', CURRENT_DATE(), CURRENT_TIME();
CREATE INDEX ID_IDX on bc2pubtator(ID);
SELECT 'fin ID index', CURRENT_DATE(), CURRENT_TIME();

#SELECT 'start ID_PMID_IDX index', CURRENT_DATE(), CURRENT_TIME();
#CREATE INDEX ID_PMID_IDX on bc2pubtator(ID, PMID);
#SELECT 'fin ID_PMID_IDX index', CURRENT_DATE(), CURRENT_TIME();