version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_pubtator
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pubtator
      MYSQL_USER: pub
      MYSQL_PASSWORD: pub
    ports:
      - 3306:3306
    volumes:
      - ${PWD}/my.cnf:/etc/mysql/conf.d/my.cnf
      - ${PWD}/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ${PWD}/../../data/mysql_data:/var/lib/mysql