ALTER INSTANCE DISABLE INNODB REDO_LOG;
commit;

LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0001.tsv' INTO TABLE bc2pubtator;
SELECT '0001.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0002.tsv' INTO TABLE bc2pubtator;
SELECT '0002.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0003.tsv' INTO TABLE bc2pubtator;
SELECT '0003.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0004.tsv' INTO TABLE bc2pubtator;
SELECT '0004.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0005.tsv' INTO TABLE bc2pubtator;
SELECT '0005.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0006.tsv' INTO TABLE bc2pubtator;
SELECT '0006.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0007.tsv' INTO TABLE bc2pubtator;
SELECT '0007.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0008.tsv' INTO TABLE bc2pubtator;
SELECT '0008.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0009.tsv' INTO TABLE bc2pubtator;
SELECT '0009.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0010.tsv' INTO TABLE bc2pubtator;
SELECT '0010.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0011.tsv' INTO TABLE bc2pubtator;
SELECT '0011.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0012.tsv' INTO TABLE bc2pubtator;
SELECT '0012.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0013.tsv' INTO TABLE bc2pubtator;
SELECT '0013.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0014.tsv' INTO TABLE bc2pubtator;
SELECT '0014.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0015.tsv' INTO TABLE bc2pubtator;
SELECT '0015.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0016.tsv' INTO TABLE bc2pubtator;
SELECT '0016.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0017.tsv' INTO TABLE bc2pubtator;
SELECT '0017.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0018.tsv' INTO TABLE bc2pubtator;
SELECT '0018.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0019.tsv' INTO TABLE bc2pubtator;
SELECT '0019.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0020.tsv' INTO TABLE bc2pubtator;
SELECT '0020.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0021.tsv' INTO TABLE bc2pubtator;
SELECT '0021.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0022.tsv' INTO TABLE bc2pubtator;
SELECT '0022.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0023.tsv' INTO TABLE bc2pubtator;
SELECT '0023.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0024.tsv' INTO TABLE bc2pubtator;
SELECT '0024.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0025.tsv' INTO TABLE bc2pubtator;
SELECT '0025.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0026.tsv' INTO TABLE bc2pubtator;
SELECT '0026.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0027.tsv' INTO TABLE bc2pubtator;
SELECT '0027.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0028.tsv' INTO TABLE bc2pubtator;
SELECT '0028.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0029.tsv' INTO TABLE bc2pubtator;
SELECT '0029.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0030.tsv' INTO TABLE bc2pubtator;
SELECT '0030.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0031.tsv' INTO TABLE bc2pubtator;
SELECT '0031.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0032.tsv' INTO TABLE bc2pubtator;
SELECT '0032.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0033.tsv' INTO TABLE bc2pubtator;
SELECT '0033.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0034.tsv' INTO TABLE bc2pubtator;
SELECT '0034.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0035.tsv' INTO TABLE bc2pubtator;
SELECT '0035.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0036.tsv' INTO TABLE bc2pubtator;
SELECT '0036.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0037.tsv' INTO TABLE bc2pubtator;
SELECT '0037.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0038.tsv' INTO TABLE bc2pubtator;
SELECT '0038.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0039.tsv' INTO TABLE bc2pubtator;
SELECT '0039.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0040.tsv' INTO TABLE bc2pubtator;
SELECT '0040.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0041.tsv' INTO TABLE bc2pubtator;
SELECT '0041.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0042.tsv' INTO TABLE bc2pubtator;
SELECT '0042.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0043.tsv' INTO TABLE bc2pubtator;
SELECT '0043.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0044.tsv' INTO TABLE bc2pubtator;
SELECT '0044.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0045.tsv' INTO TABLE bc2pubtator;
SELECT '0045.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0046.tsv' INTO TABLE bc2pubtator;
SELECT '0046.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0047.tsv' INTO TABLE bc2pubtator;
SELECT '0047.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0048.tsv' INTO TABLE bc2pubtator;
SELECT '0048.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0049.tsv' INTO TABLE bc2pubtator;
SELECT '0049.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0050.tsv' INTO TABLE bc2pubtator;
SELECT '0050.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0051.tsv' INTO TABLE bc2pubtator;
SELECT '0051.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0052.tsv' INTO TABLE bc2pubtator;
SELECT '0052.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0053.tsv' INTO TABLE bc2pubtator;
SELECT '0053.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0054.tsv' INTO TABLE bc2pubtator;
SELECT '0054.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0055.tsv' INTO TABLE bc2pubtator;
SELECT '0055.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0056.tsv' INTO TABLE bc2pubtator;
SELECT '0056.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0057.tsv' INTO TABLE bc2pubtator;
SELECT '0057.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0058.tsv' INTO TABLE bc2pubtator;
SELECT '0058.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0059.tsv' INTO TABLE bc2pubtator;
SELECT '0059.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0060.tsv' INTO TABLE bc2pubtator;
SELECT '0060.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0061.tsv' INTO TABLE bc2pubtator;
SELECT '0061.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0062.tsv' INTO TABLE bc2pubtator;
SELECT '0062.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0063.tsv' INTO TABLE bc2pubtator;
SELECT '0063.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0064.tsv' INTO TABLE bc2pubtator;
SELECT '0064.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0065.tsv' INTO TABLE bc2pubtator;
SELECT '0065.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0066.tsv' INTO TABLE bc2pubtator;
SELECT '0066.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0067.tsv' INTO TABLE bc2pubtator;
SELECT '0067.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0068.tsv' INTO TABLE bc2pubtator;
SELECT '0068.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0069.tsv' INTO TABLE bc2pubtator;
SELECT '0069.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0070.tsv' INTO TABLE bc2pubtator;
SELECT '0070.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0071.tsv' INTO TABLE bc2pubtator;
SELECT '0071.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0072.tsv' INTO TABLE bc2pubtator;
SELECT '0072.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0073.tsv' INTO TABLE bc2pubtator;
SELECT '0073.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0074.tsv' INTO TABLE bc2pubtator;
SELECT '0074.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0075.tsv' INTO TABLE bc2pubtator;
SELECT '0075.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0076.tsv' INTO TABLE bc2pubtator;
SELECT '0076.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0077.tsv' INTO TABLE bc2pubtator;
SELECT '0077.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0078.tsv' INTO TABLE bc2pubtator;
SELECT '0078.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0079.tsv' INTO TABLE bc2pubtator;
SELECT '0079.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0080.tsv' INTO TABLE bc2pubtator;
SELECT '0080.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0081.tsv' INTO TABLE bc2pubtator;
SELECT '0081.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0082.tsv' INTO TABLE bc2pubtator;
SELECT '0082.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0083.tsv' INTO TABLE bc2pubtator;
SELECT '0083.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0084.tsv' INTO TABLE bc2pubtator;
SELECT '0084.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0085.tsv' INTO TABLE bc2pubtator;
SELECT '0085.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0086.tsv' INTO TABLE bc2pubtator;
SELECT '0086.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0087.tsv' INTO TABLE bc2pubtator;
SELECT '0087.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0088.tsv' INTO TABLE bc2pubtator;
SELECT '0088.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0089.tsv' INTO TABLE bc2pubtator;
SELECT '0089.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0090.tsv' INTO TABLE bc2pubtator;
SELECT '0090.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0091.tsv' INTO TABLE bc2pubtator;
SELECT '0091.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0092.tsv' INTO TABLE bc2pubtator;
SELECT '0092.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0093.tsv' INTO TABLE bc2pubtator;
SELECT '0093.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0094.tsv' INTO TABLE bc2pubtator;
SELECT '0094.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0095.tsv' INTO TABLE bc2pubtator;
SELECT '0095.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0096.tsv' INTO TABLE bc2pubtator;
SELECT '0096.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0097.tsv' INTO TABLE bc2pubtator;
SELECT '0097.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0098.tsv' INTO TABLE bc2pubtator;
SELECT '0098.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0099.tsv' INTO TABLE bc2pubtator;
SELECT '0099.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0100.tsv' INTO TABLE bc2pubtator;
SELECT '0100.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0101.tsv' INTO TABLE bc2pubtator;
SELECT '0101.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0102.tsv' INTO TABLE bc2pubtator;
SELECT '0102.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0103.tsv' INTO TABLE bc2pubtator;
SELECT '0103.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0104.tsv' INTO TABLE bc2pubtator;
SELECT '0104.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0105.tsv' INTO TABLE bc2pubtator;
SELECT '0105.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0106.tsv' INTO TABLE bc2pubtator;
SELECT '0106.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0107.tsv' INTO TABLE bc2pubtator;
SELECT '0107.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0108.tsv' INTO TABLE bc2pubtator;
SELECT '0108.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0109.tsv' INTO TABLE bc2pubtator;
SELECT '0109.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0110.tsv' INTO TABLE bc2pubtator;
SELECT '0110.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0111.tsv' INTO TABLE bc2pubtator;
SELECT '0111.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0112.tsv' INTO TABLE bc2pubtator;
SELECT '0112.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0113.tsv' INTO TABLE bc2pubtator;
SELECT '0113.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0114.tsv' INTO TABLE bc2pubtator;
SELECT '0114.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0115.tsv' INTO TABLE bc2pubtator;
SELECT '0115.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0116.tsv' INTO TABLE bc2pubtator;
SELECT '0116.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0117.tsv' INTO TABLE bc2pubtator;
SELECT '0117.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0118.tsv' INTO TABLE bc2pubtator;
SELECT '0118.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0119.tsv' INTO TABLE bc2pubtator;
SELECT '0119.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0120.tsv' INTO TABLE bc2pubtator;
SELECT '0120.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0121.tsv' INTO TABLE bc2pubtator;
SELECT '0121.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0122.tsv' INTO TABLE bc2pubtator;
SELECT '0122.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0123.tsv' INTO TABLE bc2pubtator;
SELECT '0123.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0124.tsv' INTO TABLE bc2pubtator;
SELECT '0124.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0125.tsv' INTO TABLE bc2pubtator;
SELECT '0125.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0126.tsv' INTO TABLE bc2pubtator;
SELECT '0126.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0127.tsv' INTO TABLE bc2pubtator;
SELECT '0127.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0128.tsv' INTO TABLE bc2pubtator;
SELECT '0128.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0129.tsv' INTO TABLE bc2pubtator;
SELECT '0129.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0130.tsv' INTO TABLE bc2pubtator;
SELECT '0130.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0131.tsv' INTO TABLE bc2pubtator;
SELECT '0131.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0132.tsv' INTO TABLE bc2pubtator;
SELECT '0132.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0133.tsv' INTO TABLE bc2pubtator;
SELECT '0133.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0134.tsv' INTO TABLE bc2pubtator;
SELECT '0134.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0135.tsv' INTO TABLE bc2pubtator;
SELECT '0135.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0136.tsv' INTO TABLE bc2pubtator;
SELECT '0136.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0137.tsv' INTO TABLE bc2pubtator;
SELECT '0137.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0138.tsv' INTO TABLE bc2pubtator;
SELECT '0138.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0139.tsv' INTO TABLE bc2pubtator;
SELECT '0139.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0140.tsv' INTO TABLE bc2pubtator;
SELECT '0140.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0141.tsv' INTO TABLE bc2pubtator;
SELECT '0141.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0142.tsv' INTO TABLE bc2pubtator;
SELECT '0142.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0143.tsv' INTO TABLE bc2pubtator;
SELECT '0143.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0144.tsv' INTO TABLE bc2pubtator;
SELECT '0144.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0145.tsv' INTO TABLE bc2pubtator;
SELECT '0145.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0146.tsv' INTO TABLE bc2pubtator;
SELECT '0146.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0147.tsv' INTO TABLE bc2pubtator;
SELECT '0147.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0148.tsv' INTO TABLE bc2pubtator;
SELECT '0148.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0149.tsv' INTO TABLE bc2pubtator;
SELECT '0149.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0150.tsv' INTO TABLE bc2pubtator;
SELECT '0150.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0151.tsv' INTO TABLE bc2pubtator;
SELECT '0151.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0152.tsv' INTO TABLE bc2pubtator;
SELECT '0152.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0153.tsv' INTO TABLE bc2pubtator;
SELECT '0153.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0154.tsv' INTO TABLE bc2pubtator;
SELECT '0154.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0155.tsv' INTO TABLE bc2pubtator;
SELECT '0155.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0156.tsv' INTO TABLE bc2pubtator;
SELECT '0156.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0157.tsv' INTO TABLE bc2pubtator;
SELECT '0157.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0158.tsv' INTO TABLE bc2pubtator;
SELECT '0158.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0159.tsv' INTO TABLE bc2pubtator;
SELECT '0159.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0160.tsv' INTO TABLE bc2pubtator;
SELECT '0160.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0161.tsv' INTO TABLE bc2pubtator;
SELECT '0161.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0162.tsv' INTO TABLE bc2pubtator;
SELECT '0162.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0163.tsv' INTO TABLE bc2pubtator;
SELECT '0163.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0164.tsv' INTO TABLE bc2pubtator;
SELECT '0164.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0165.tsv' INTO TABLE bc2pubtator;
SELECT '0165.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0166.tsv' INTO TABLE bc2pubtator;
SELECT '0166.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0167.tsv' INTO TABLE bc2pubtator;
SELECT '0167.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0168.tsv' INTO TABLE bc2pubtator;
SELECT '0168.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0169.tsv' INTO TABLE bc2pubtator;
SELECT '0169.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0170.tsv' INTO TABLE bc2pubtator;
SELECT '0170.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0171.tsv' INTO TABLE bc2pubtator;
SELECT '0171.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0172.tsv' INTO TABLE bc2pubtator;
SELECT '0172.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0173.tsv' INTO TABLE bc2pubtator;
SELECT '0173.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0174.tsv' INTO TABLE bc2pubtator;
SELECT '0174.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0175.tsv' INTO TABLE bc2pubtator;
SELECT '0175.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0176.tsv' INTO TABLE bc2pubtator;
SELECT '0176.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0177.tsv' INTO TABLE bc2pubtator;
SELECT '0177.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0178.tsv' INTO TABLE bc2pubtator;
SELECT '0178.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0179.tsv' INTO TABLE bc2pubtator;
SELECT '0179.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0180.tsv' INTO TABLE bc2pubtator;
SELECT '0180.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0181.tsv' INTO TABLE bc2pubtator;
SELECT '0181.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0182.tsv' INTO TABLE bc2pubtator;
SELECT '0182.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0183.tsv' INTO TABLE bc2pubtator;
SELECT '0183.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0184.tsv' INTO TABLE bc2pubtator;
SELECT '0184.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0185.tsv' INTO TABLE bc2pubtator;
SELECT '0185.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0186.tsv' INTO TABLE bc2pubtator;
SELECT '0186.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0187.tsv' INTO TABLE bc2pubtator;
SELECT '0187.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0188.tsv' INTO TABLE bc2pubtator;
SELECT '0188.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0189.tsv' INTO TABLE bc2pubtator;
SELECT '0189.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0190.tsv' INTO TABLE bc2pubtator;
SELECT '0190.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0191.tsv' INTO TABLE bc2pubtator;
SELECT '0191.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0192.tsv' INTO TABLE bc2pubtator;
SELECT '0192.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0193.tsv' INTO TABLE bc2pubtator;
SELECT '0193.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0194.tsv' INTO TABLE bc2pubtator;
SELECT '0194.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0195.tsv' INTO TABLE bc2pubtator;
SELECT '0195.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0196.tsv' INTO TABLE bc2pubtator;
SELECT '0196.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0197.tsv' INTO TABLE bc2pubtator;
SELECT '0197.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0198.tsv' INTO TABLE bc2pubtator;
SELECT '0198.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0199.tsv' INTO TABLE bc2pubtator;
SELECT '0199.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0200.tsv' INTO TABLE bc2pubtator;
SELECT '0200.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0201.tsv' INTO TABLE bc2pubtator;
SELECT '0201.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0202.tsv' INTO TABLE bc2pubtator;
SELECT '0202.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0203.tsv' INTO TABLE bc2pubtator;
SELECT '0203.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0204.tsv' INTO TABLE bc2pubtator;
SELECT '0204.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0205.tsv' INTO TABLE bc2pubtator;
SELECT '0205.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0206.tsv' INTO TABLE bc2pubtator;
SELECT '0206.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0207.tsv' INTO TABLE bc2pubtator;
SELECT '0207.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0208.tsv' INTO TABLE bc2pubtator;
SELECT '0208.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0209.tsv' INTO TABLE bc2pubtator;
SELECT '0209.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0210.tsv' INTO TABLE bc2pubtator;
SELECT '0210.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0211.tsv' INTO TABLE bc2pubtator;
SELECT '0211.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0212.tsv' INTO TABLE bc2pubtator;
SELECT '0212.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0213.tsv' INTO TABLE bc2pubtator;
SELECT '0213.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0214.tsv' INTO TABLE bc2pubtator;
SELECT '0214.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0215.tsv' INTO TABLE bc2pubtator;
SELECT '0215.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0216.tsv' INTO TABLE bc2pubtator;
SELECT '0216.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0217.tsv' INTO TABLE bc2pubtator;
SELECT '0217.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0218.tsv' INTO TABLE bc2pubtator;
SELECT '0218.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0219.tsv' INTO TABLE bc2pubtator;
SELECT '0219.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0220.tsv' INTO TABLE bc2pubtator;
SELECT '0220.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0221.tsv' INTO TABLE bc2pubtator;
SELECT '0221.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0222.tsv' INTO TABLE bc2pubtator;
SELECT '0222.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0223.tsv' INTO TABLE bc2pubtator;
SELECT '0223.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0224.tsv' INTO TABLE bc2pubtator;
SELECT '0224.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0225.tsv' INTO TABLE bc2pubtator;
SELECT '0225.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0226.tsv' INTO TABLE bc2pubtator;
SELECT '0226.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0227.tsv' INTO TABLE bc2pubtator;
SELECT '0227.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0228.tsv' INTO TABLE bc2pubtator;
SELECT '0228.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0229.tsv' INTO TABLE bc2pubtator;
SELECT '0229.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0230.tsv' INTO TABLE bc2pubtator;
SELECT '0230.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0231.tsv' INTO TABLE bc2pubtator;
SELECT '0231.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0232.tsv' INTO TABLE bc2pubtator;
SELECT '0232.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0233.tsv' INTO TABLE bc2pubtator;
SELECT '0233.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0234.tsv' INTO TABLE bc2pubtator;
SELECT '0234.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0235.tsv' INTO TABLE bc2pubtator;
SELECT '0235.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0236.tsv' INTO TABLE bc2pubtator;
SELECT '0236.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0237.tsv' INTO TABLE bc2pubtator;
SELECT '0237.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0238.tsv' INTO TABLE bc2pubtator;
SELECT '0238.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0239.tsv' INTO TABLE bc2pubtator;
SELECT '0239.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0240.tsv' INTO TABLE bc2pubtator;
SELECT '0240.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0241.tsv' INTO TABLE bc2pubtator;
SELECT '0241.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0242.tsv' INTO TABLE bc2pubtator;
SELECT '0242.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0243.tsv' INTO TABLE bc2pubtator;
SELECT '0243.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0244.tsv' INTO TABLE bc2pubtator;
SELECT '0244.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0245.tsv' INTO TABLE bc2pubtator;
SELECT '0245.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0246.tsv' INTO TABLE bc2pubtator;
SELECT '0246.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0247.tsv' INTO TABLE bc2pubtator;
SELECT '0247.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0248.tsv' INTO TABLE bc2pubtator;
SELECT '0248.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0249.tsv' INTO TABLE bc2pubtator;
SELECT '0249.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0250.tsv' INTO TABLE bc2pubtator;
SELECT '0250.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0251.tsv' INTO TABLE bc2pubtator;
SELECT '0251.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0252.tsv' INTO TABLE bc2pubtator;
SELECT '0252.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0253.tsv' INTO TABLE bc2pubtator;
SELECT '0253.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0254.tsv' INTO TABLE bc2pubtator;
SELECT '0254.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0255.tsv' INTO TABLE bc2pubtator;
SELECT '0255.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0256.tsv' INTO TABLE bc2pubtator;
SELECT '0256.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0257.tsv' INTO TABLE bc2pubtator;
SELECT '0257.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0258.tsv' INTO TABLE bc2pubtator;
SELECT '0258.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0259.tsv' INTO TABLE bc2pubtator;
SELECT '0259.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0260.tsv' INTO TABLE bc2pubtator;
SELECT '0260.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0261.tsv' INTO TABLE bc2pubtator;
SELECT '0261.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0262.tsv' INTO TABLE bc2pubtator;
SELECT '0262.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0263.tsv' INTO TABLE bc2pubtator;
SELECT '0263.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0264.tsv' INTO TABLE bc2pubtator;
SELECT '0264.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0265.tsv' INTO TABLE bc2pubtator;
SELECT '0265.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0266.tsv' INTO TABLE bc2pubtator;
SELECT '0266.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0267.tsv' INTO TABLE bc2pubtator;
SELECT '0267.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0268.tsv' INTO TABLE bc2pubtator;
SELECT '0268.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0269.tsv' INTO TABLE bc2pubtator;
SELECT '0269.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0270.tsv' INTO TABLE bc2pubtator;
SELECT '0270.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0271.tsv' INTO TABLE bc2pubtator;
SELECT '0271.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0272.tsv' INTO TABLE bc2pubtator;
SELECT '0272.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0273.tsv' INTO TABLE bc2pubtator;
SELECT '0273.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0274.tsv' INTO TABLE bc2pubtator;
SELECT '0274.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0275.tsv' INTO TABLE bc2pubtator;
SELECT '0275.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0276.tsv' INTO TABLE bc2pubtator;
SELECT '0276.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0277.tsv' INTO TABLE bc2pubtator;
SELECT '0277.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0278.tsv' INTO TABLE bc2pubtator;
SELECT '0278.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0279.tsv' INTO TABLE bc2pubtator;
SELECT '0279.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0280.tsv' INTO TABLE bc2pubtator;
SELECT '0280.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0281.tsv' INTO TABLE bc2pubtator;
SELECT '0281.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0282.tsv' INTO TABLE bc2pubtator;
SELECT '0282.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0283.tsv' INTO TABLE bc2pubtator;
SELECT '0283.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0284.tsv' INTO TABLE bc2pubtator;
SELECT '0284.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0285.tsv' INTO TABLE bc2pubtator;
SELECT '0285.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0286.tsv' INTO TABLE bc2pubtator;
SELECT '0286.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0287.tsv' INTO TABLE bc2pubtator;
SELECT '0287.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0288.tsv' INTO TABLE bc2pubtator;
SELECT '0288.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0289.tsv' INTO TABLE bc2pubtator;
SELECT '0289.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0290.tsv' INTO TABLE bc2pubtator;
SELECT '0290.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0291.tsv' INTO TABLE bc2pubtator;
SELECT '0291.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0292.tsv' INTO TABLE bc2pubtator;
SELECT '0292.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0293.tsv' INTO TABLE bc2pubtator;
SELECT '0293.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0294.tsv' INTO TABLE bc2pubtator;
SELECT '0294.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0295.tsv' INTO TABLE bc2pubtator;
SELECT '0295.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0296.tsv' INTO TABLE bc2pubtator;
SELECT '0296.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0297.tsv' INTO TABLE bc2pubtator;
SELECT '0297.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0298.tsv' INTO TABLE bc2pubtator;
SELECT '0298.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0299.tsv' INTO TABLE bc2pubtator;
SELECT '0299.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0300.tsv' INTO TABLE bc2pubtator;
SELECT '0300.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0301.tsv' INTO TABLE bc2pubtator;
SELECT '0301.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0302.tsv' INTO TABLE bc2pubtator;
SELECT '0302.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0303.tsv' INTO TABLE bc2pubtator;
SELECT '0303.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0304.tsv' INTO TABLE bc2pubtator;
SELECT '0304.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0305.tsv' INTO TABLE bc2pubtator;
SELECT '0305.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0306.tsv' INTO TABLE bc2pubtator;
SELECT '0306.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0307.tsv' INTO TABLE bc2pubtator;
SELECT '0307.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0308.tsv' INTO TABLE bc2pubtator;
SELECT '0308.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0309.tsv' INTO TABLE bc2pubtator;
SELECT '0309.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0310.tsv' INTO TABLE bc2pubtator;
SELECT '0310.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0311.tsv' INTO TABLE bc2pubtator;
SELECT '0311.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0312.tsv' INTO TABLE bc2pubtator;
SELECT '0312.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0313.tsv' INTO TABLE bc2pubtator;
SELECT '0313.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0314.tsv' INTO TABLE bc2pubtator;
SELECT '0314.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0315.tsv' INTO TABLE bc2pubtator;
SELECT '0315.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0316.tsv' INTO TABLE bc2pubtator;
SELECT '0316.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0317.tsv' INTO TABLE bc2pubtator;
SELECT '0317.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0318.tsv' INTO TABLE bc2pubtator;
SELECT '0318.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0319.tsv' INTO TABLE bc2pubtator;
SELECT '0319.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0320.tsv' INTO TABLE bc2pubtator;
SELECT '0320.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0321.tsv' INTO TABLE bc2pubtator;
SELECT '0321.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0322.tsv' INTO TABLE bc2pubtator;
SELECT '0322.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0323.tsv' INTO TABLE bc2pubtator;
SELECT '0323.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0324.tsv' INTO TABLE bc2pubtator;
SELECT '0324.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0325.tsv' INTO TABLE bc2pubtator;
SELECT '0325.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0326.tsv' INTO TABLE bc2pubtator;
SELECT '0326.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0327.tsv' INTO TABLE bc2pubtator;
SELECT '0327.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0328.tsv' INTO TABLE bc2pubtator;
SELECT '0328.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0329.tsv' INTO TABLE bc2pubtator;
SELECT '0329.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0330.tsv' INTO TABLE bc2pubtator;
SELECT '0330.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0331.tsv' INTO TABLE bc2pubtator;
SELECT '0331.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0332.tsv' INTO TABLE bc2pubtator;
SELECT '0332.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0333.tsv' INTO TABLE bc2pubtator;
SELECT '0333.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0334.tsv' INTO TABLE bc2pubtator;
SELECT '0334.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0335.tsv' INTO TABLE bc2pubtator;
SELECT '0335.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0336.tsv' INTO TABLE bc2pubtator;
SELECT '0336.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0337.tsv' INTO TABLE bc2pubtator;
SELECT '0337.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0338.tsv' INTO TABLE bc2pubtator;
SELECT '0338.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0339.tsv' INTO TABLE bc2pubtator;
SELECT '0339.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0340.tsv' INTO TABLE bc2pubtator;
SELECT '0340.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0341.tsv' INTO TABLE bc2pubtator;
SELECT '0341.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0342.tsv' INTO TABLE bc2pubtator;
SELECT '0342.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0343.tsv' INTO TABLE bc2pubtator;
SELECT '0343.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0344.tsv' INTO TABLE bc2pubtator;
SELECT '0344.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0345.tsv' INTO TABLE bc2pubtator;
SELECT '0345.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0346.tsv' INTO TABLE bc2pubtator;
SELECT '0346.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0347.tsv' INTO TABLE bc2pubtator;
SELECT '0347.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0348.tsv' INTO TABLE bc2pubtator;
SELECT '0348.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0349.tsv' INTO TABLE bc2pubtator;
SELECT '0349.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0350.tsv' INTO TABLE bc2pubtator;
SELECT '0350.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0351.tsv' INTO TABLE bc2pubtator;
SELECT '0351.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0352.tsv' INTO TABLE bc2pubtator;
SELECT '0352.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0353.tsv' INTO TABLE bc2pubtator;
SELECT '0353.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0354.tsv' INTO TABLE bc2pubtator;
SELECT '0354.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0355.tsv' INTO TABLE bc2pubtator;
SELECT '0355.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0356.tsv' INTO TABLE bc2pubtator;
SELECT '0356.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0357.tsv' INTO TABLE bc2pubtator;
SELECT '0357.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0358.tsv' INTO TABLE bc2pubtator;
SELECT '0358.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0359.tsv' INTO TABLE bc2pubtator;
SELECT '0359.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0360.tsv' INTO TABLE bc2pubtator;
SELECT '0360.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0361.tsv' INTO TABLE bc2pubtator;
SELECT '0361.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0362.tsv' INTO TABLE bc2pubtator;
SELECT '0362.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0363.tsv' INTO TABLE bc2pubtator;
SELECT '0363.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0364.tsv' INTO TABLE bc2pubtator;
SELECT '0364.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0365.tsv' INTO TABLE bc2pubtator;
SELECT '0365.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0366.tsv' INTO TABLE bc2pubtator;
SELECT '0366.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0367.tsv' INTO TABLE bc2pubtator;
SELECT '0367.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0368.tsv' INTO TABLE bc2pubtator;
SELECT '0368.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0369.tsv' INTO TABLE bc2pubtator;
SELECT '0369.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0370.tsv' INTO TABLE bc2pubtator;
SELECT '0370.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0371.tsv' INTO TABLE bc2pubtator;
SELECT '0371.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0372.tsv' INTO TABLE bc2pubtator;
SELECT '0372.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0373.tsv' INTO TABLE bc2pubtator;
SELECT '0373.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0374.tsv' INTO TABLE bc2pubtator;
SELECT '0374.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0375.tsv' INTO TABLE bc2pubtator;
SELECT '0375.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0376.tsv' INTO TABLE bc2pubtator;
SELECT '0376.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0377.tsv' INTO TABLE bc2pubtator;
SELECT '0377.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0378.tsv' INTO TABLE bc2pubtator;
SELECT '0378.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0379.tsv' INTO TABLE bc2pubtator;
SELECT '0379.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0380.tsv' INTO TABLE bc2pubtator;
SELECT '0380.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0381.tsv' INTO TABLE bc2pubtator;
SELECT '0381.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0382.tsv' INTO TABLE bc2pubtator;
SELECT '0382.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0383.tsv' INTO TABLE bc2pubtator;
SELECT '0383.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0384.tsv' INTO TABLE bc2pubtator;
SELECT '0384.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0385.tsv' INTO TABLE bc2pubtator;
SELECT '0385.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0386.tsv' INTO TABLE bc2pubtator;
SELECT '0386.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0387.tsv' INTO TABLE bc2pubtator;
SELECT '0387.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0388.tsv' INTO TABLE bc2pubtator;
SELECT '0388.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0389.tsv' INTO TABLE bc2pubtator;
SELECT '0389.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0390.tsv' INTO TABLE bc2pubtator;
SELECT '0390.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0391.tsv' INTO TABLE bc2pubtator;
SELECT '0391.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0392.tsv' INTO TABLE bc2pubtator;
SELECT '0392.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0393.tsv' INTO TABLE bc2pubtator;
SELECT '0393.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0394.tsv' INTO TABLE bc2pubtator;
SELECT '0394.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0395.tsv' INTO TABLE bc2pubtator;
SELECT '0395.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0396.tsv' INTO TABLE bc2pubtator;
SELECT '0396.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0397.tsv' INTO TABLE bc2pubtator;
SELECT '0397.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0398.tsv' INTO TABLE bc2pubtator;
SELECT '0398.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0399.tsv' INTO TABLE bc2pubtator;
SELECT '0399.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0400.tsv' INTO TABLE bc2pubtator;
SELECT '0400.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0401.tsv' INTO TABLE bc2pubtator;
SELECT '0401.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0402.tsv' INTO TABLE bc2pubtator;
SELECT '0402.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0403.tsv' INTO TABLE bc2pubtator;
SELECT '0403.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0404.tsv' INTO TABLE bc2pubtator;
SELECT '0404.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0405.tsv' INTO TABLE bc2pubtator;
SELECT '0405.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0406.tsv' INTO TABLE bc2pubtator;
SELECT '0406.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0407.tsv' INTO TABLE bc2pubtator;
SELECT '0407.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0408.tsv' INTO TABLE bc2pubtator;
SELECT '0408.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0409.tsv' INTO TABLE bc2pubtator;
SELECT '0409.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0410.tsv' INTO TABLE bc2pubtator;
SELECT '0410.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0411.tsv' INTO TABLE bc2pubtator;
SELECT '0411.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0412.tsv' INTO TABLE bc2pubtator;
SELECT '0412.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0413.tsv' INTO TABLE bc2pubtator;
SELECT '0413.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0414.tsv' INTO TABLE bc2pubtator;
SELECT '0414.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0415.tsv' INTO TABLE bc2pubtator;
SELECT '0415.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0416.tsv' INTO TABLE bc2pubtator;
SELECT '0416.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0417.tsv' INTO TABLE bc2pubtator;
SELECT '0417.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0418.tsv' INTO TABLE bc2pubtator;
SELECT '0418.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0419.tsv' INTO TABLE bc2pubtator;
SELECT '0419.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0420.tsv' INTO TABLE bc2pubtator;
SELECT '0420.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0421.tsv' INTO TABLE bc2pubtator;
SELECT '0421.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0422.tsv' INTO TABLE bc2pubtator;
SELECT '0422.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0423.tsv' INTO TABLE bc2pubtator;
SELECT '0423.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0424.tsv' INTO TABLE bc2pubtator;
SELECT '0424.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0425.tsv' INTO TABLE bc2pubtator;
SELECT '0425.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0426.tsv' INTO TABLE bc2pubtator;
SELECT '0426.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0427.tsv' INTO TABLE bc2pubtator;
SELECT '0427.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0428.tsv' INTO TABLE bc2pubtator;
SELECT '0428.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0429.tsv' INTO TABLE bc2pubtator;
SELECT '0429.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0430.tsv' INTO TABLE bc2pubtator;
SELECT '0430.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0431.tsv' INTO TABLE bc2pubtator;
SELECT '0431.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0432.tsv' INTO TABLE bc2pubtator;
SELECT '0432.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0433.tsv' INTO TABLE bc2pubtator;
SELECT '0433.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0434.tsv' INTO TABLE bc2pubtator;
SELECT '0434.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0435.tsv' INTO TABLE bc2pubtator;
SELECT '0435.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0436.tsv' INTO TABLE bc2pubtator;
SELECT '0436.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0437.tsv' INTO TABLE bc2pubtator;
SELECT '0437.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0438.tsv' INTO TABLE bc2pubtator;
SELECT '0438.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0439.tsv' INTO TABLE bc2pubtator;
SELECT '0439.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0440.tsv' INTO TABLE bc2pubtator;
SELECT '0440.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0441.tsv' INTO TABLE bc2pubtator;
SELECT '0441.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0442.tsv' INTO TABLE bc2pubtator;
SELECT '0442.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0443.tsv' INTO TABLE bc2pubtator;
SELECT '0443.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0444.tsv' INTO TABLE bc2pubtator;
SELECT '0444.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0445.tsv' INTO TABLE bc2pubtator;
SELECT '0445.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0446.tsv' INTO TABLE bc2pubtator;
SELECT '0446.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0447.tsv' INTO TABLE bc2pubtator;
SELECT '0447.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0448.tsv' INTO TABLE bc2pubtator;
SELECT '0448.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0449.tsv' INTO TABLE bc2pubtator;
SELECT '0449.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0450.tsv' INTO TABLE bc2pubtator;
SELECT '0450.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0451.tsv' INTO TABLE bc2pubtator;
SELECT '0451.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0452.tsv' INTO TABLE bc2pubtator;
SELECT '0452.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0453.tsv' INTO TABLE bc2pubtator;
SELECT '0453.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0454.tsv' INTO TABLE bc2pubtator;
SELECT '0454.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0455.tsv' INTO TABLE bc2pubtator;
SELECT '0455.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0456.tsv' INTO TABLE bc2pubtator;
SELECT '0456.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0457.tsv' INTO TABLE bc2pubtator;
SELECT '0457.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0458.tsv' INTO TABLE bc2pubtator;
SELECT '0458.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0459.tsv' INTO TABLE bc2pubtator;
SELECT '0459.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0460.tsv' INTO TABLE bc2pubtator;
SELECT '0460.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0461.tsv' INTO TABLE bc2pubtator;
SELECT '0461.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0462.tsv' INTO TABLE bc2pubtator;
SELECT '0462.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0463.tsv' INTO TABLE bc2pubtator;
SELECT '0463.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0464.tsv' INTO TABLE bc2pubtator;
SELECT '0464.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0465.tsv' INTO TABLE bc2pubtator;
SELECT '0465.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0466.tsv' INTO TABLE bc2pubtator;
SELECT '0466.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0467.tsv' INTO TABLE bc2pubtator;
SELECT '0467.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0468.tsv' INTO TABLE bc2pubtator;
SELECT '0468.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0469.tsv' INTO TABLE bc2pubtator;
SELECT '0469.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0470.tsv' INTO TABLE bc2pubtator;
SELECT '0470.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0471.tsv' INTO TABLE bc2pubtator;
SELECT '0471.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0472.tsv' INTO TABLE bc2pubtator;
SELECT '0472.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0473.tsv' INTO TABLE bc2pubtator;
SELECT '0473.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0474.tsv' INTO TABLE bc2pubtator;
SELECT '0474.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0475.tsv' INTO TABLE bc2pubtator;
SELECT '0475.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0476.tsv' INTO TABLE bc2pubtator;
SELECT '0476.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0477.tsv' INTO TABLE bc2pubtator;
SELECT '0477.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0478.tsv' INTO TABLE bc2pubtator;
SELECT '0478.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0479.tsv' INTO TABLE bc2pubtator;
SELECT '0479.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0480.tsv' INTO TABLE bc2pubtator;
SELECT '0480.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0481.tsv' INTO TABLE bc2pubtator;
SELECT '0481.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0482.tsv' INTO TABLE bc2pubtator;
SELECT '0482.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0483.tsv' INTO TABLE bc2pubtator;
SELECT '0483.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0484.tsv' INTO TABLE bc2pubtator;
SELECT '0484.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0485.tsv' INTO TABLE bc2pubtator;
SELECT '0485.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0486.tsv' INTO TABLE bc2pubtator;
SELECT '0486.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0487.tsv' INTO TABLE bc2pubtator;
SELECT '0487.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0488.tsv' INTO TABLE bc2pubtator;
SELECT '0488.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0489.tsv' INTO TABLE bc2pubtator;
SELECT '0489.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0490.tsv' INTO TABLE bc2pubtator;
SELECT '0490.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0491.tsv' INTO TABLE bc2pubtator;
SELECT '0491.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0492.tsv' INTO TABLE bc2pubtator;
SELECT '0492.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0493.tsv' INTO TABLE bc2pubtator;
SELECT '0493.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0494.tsv' INTO TABLE bc2pubtator;
SELECT '0494.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0495.tsv' INTO TABLE bc2pubtator;
SELECT '0495.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0496.tsv' INTO TABLE bc2pubtator;
SELECT '0496.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0497.tsv' INTO TABLE bc2pubtator;
SELECT '0497.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0498.tsv' INTO TABLE bc2pubtator;
SELECT '0498.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0499.tsv' INTO TABLE bc2pubtator;
SELECT '0499.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0500.tsv' INTO TABLE bc2pubtator;
SELECT '0500.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0501.tsv' INTO TABLE bc2pubtator;
SELECT '0501.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0502.tsv' INTO TABLE bc2pubtator;
SELECT '0502.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0503.tsv' INTO TABLE bc2pubtator;
SELECT '0503.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0504.tsv' INTO TABLE bc2pubtator;
SELECT '0504.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0505.tsv' INTO TABLE bc2pubtator;
SELECT '0505.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0506.tsv' INTO TABLE bc2pubtator;
SELECT '0506.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0507.tsv' INTO TABLE bc2pubtator;
SELECT '0507.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0508.tsv' INTO TABLE bc2pubtator;
SELECT '0508.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0509.tsv' INTO TABLE bc2pubtator;
SELECT '0509.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0510.tsv' INTO TABLE bc2pubtator;
SELECT '0510.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0511.tsv' INTO TABLE bc2pubtator;
SELECT '0511.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0512.tsv' INTO TABLE bc2pubtator;
SELECT '0512.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0513.tsv' INTO TABLE bc2pubtator;
SELECT '0513.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0514.tsv' INTO TABLE bc2pubtator;
SELECT '0514.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0515.tsv' INTO TABLE bc2pubtator;
SELECT '0515.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0516.tsv' INTO TABLE bc2pubtator;
SELECT '0516.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0517.tsv' INTO TABLE bc2pubtator;
SELECT '0517.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0518.tsv' INTO TABLE bc2pubtator;
SELECT '0518.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0519.tsv' INTO TABLE bc2pubtator;
SELECT '0519.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0520.tsv' INTO TABLE bc2pubtator;
SELECT '0520.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0521.tsv' INTO TABLE bc2pubtator;
SELECT '0521.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0522.tsv' INTO TABLE bc2pubtator;
SELECT '0522.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0523.tsv' INTO TABLE bc2pubtator;
SELECT '0523.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0524.tsv' INTO TABLE bc2pubtator;
SELECT '0524.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0525.tsv' INTO TABLE bc2pubtator;
SELECT '0525.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0526.tsv' INTO TABLE bc2pubtator;
SELECT '0526.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0527.tsv' INTO TABLE bc2pubtator;
SELECT '0527.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0528.tsv' INTO TABLE bc2pubtator;
SELECT '0528.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0529.tsv' INTO TABLE bc2pubtator;
SELECT '0529.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0530.tsv' INTO TABLE bc2pubtator;
SELECT '0530.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0531.tsv' INTO TABLE bc2pubtator;
SELECT '0531.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0532.tsv' INTO TABLE bc2pubtator;
SELECT '0532.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0533.tsv' INTO TABLE bc2pubtator;
SELECT '0533.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0534.tsv' INTO TABLE bc2pubtator;
SELECT '0534.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0535.tsv' INTO TABLE bc2pubtator;
SELECT '0535.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0536.tsv' INTO TABLE bc2pubtator;
SELECT '0536.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0537.tsv' INTO TABLE bc2pubtator;
SELECT '0537.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0538.tsv' INTO TABLE bc2pubtator;
SELECT '0538.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0539.tsv' INTO TABLE bc2pubtator;
SELECT '0539.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0540.tsv' INTO TABLE bc2pubtator;
SELECT '0540.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0541.tsv' INTO TABLE bc2pubtator;
SELECT '0541.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0542.tsv' INTO TABLE bc2pubtator;
SELECT '0542.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0543.tsv' INTO TABLE bc2pubtator;
SELECT '0543.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0544.tsv' INTO TABLE bc2pubtator;
SELECT '0544.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0545.tsv' INTO TABLE bc2pubtator;
SELECT '0545.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0546.tsv' INTO TABLE bc2pubtator;
SELECT '0546.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0547.tsv' INTO TABLE bc2pubtator;
SELECT '0547.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0548.tsv' INTO TABLE bc2pubtator;
SELECT '0548.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0549.tsv' INTO TABLE bc2pubtator;
SELECT '0549.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0550.tsv' INTO TABLE bc2pubtator;
SELECT '0550.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0551.tsv' INTO TABLE bc2pubtator;
SELECT '0551.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0552.tsv' INTO TABLE bc2pubtator;
SELECT '0552.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0553.tsv' INTO TABLE bc2pubtator;
SELECT '0553.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0554.tsv' INTO TABLE bc2pubtator;
SELECT '0554.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0555.tsv' INTO TABLE bc2pubtator;
SELECT '0555.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0556.tsv' INTO TABLE bc2pubtator;
SELECT '0556.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0557.tsv' INTO TABLE bc2pubtator;
SELECT '0557.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0558.tsv' INTO TABLE bc2pubtator;
SELECT '0558.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0559.tsv' INTO TABLE bc2pubtator;
SELECT '0559.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0560.tsv' INTO TABLE bc2pubtator;
SELECT '0560.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0561.tsv' INTO TABLE bc2pubtator;
SELECT '0561.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0562.tsv' INTO TABLE bc2pubtator;
SELECT '0562.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0563.tsv' INTO TABLE bc2pubtator;
SELECT '0563.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0564.tsv' INTO TABLE bc2pubtator;
SELECT '0564.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0565.tsv' INTO TABLE bc2pubtator;
SELECT '0565.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0566.tsv' INTO TABLE bc2pubtator;
SELECT '0566.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0567.tsv' INTO TABLE bc2pubtator;
SELECT '0567.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0568.tsv' INTO TABLE bc2pubtator;
SELECT '0568.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0569.tsv' INTO TABLE bc2pubtator;
SELECT '0569.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0570.tsv' INTO TABLE bc2pubtator;
SELECT '0570.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0571.tsv' INTO TABLE bc2pubtator;
SELECT '0571.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0572.tsv' INTO TABLE bc2pubtator;
SELECT '0572.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0573.tsv' INTO TABLE bc2pubtator;
SELECT '0573.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0574.tsv' INTO TABLE bc2pubtator;
SELECT '0574.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0575.tsv' INTO TABLE bc2pubtator;
SELECT '0575.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0576.tsv' INTO TABLE bc2pubtator;
SELECT '0576.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0577.tsv' INTO TABLE bc2pubtator;
SELECT '0577.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0578.tsv' INTO TABLE bc2pubtator;
SELECT '0578.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0579.tsv' INTO TABLE bc2pubtator;
SELECT '0579.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0580.tsv' INTO TABLE bc2pubtator;
SELECT '0580.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0581.tsv' INTO TABLE bc2pubtator;
SELECT '0581.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0582.tsv' INTO TABLE bc2pubtator;
SELECT '0582.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0583.tsv' INTO TABLE bc2pubtator;
SELECT '0583.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0584.tsv' INTO TABLE bc2pubtator;
SELECT '0584.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0585.tsv' INTO TABLE bc2pubtator;
SELECT '0585.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0586.tsv' INTO TABLE bc2pubtator;
SELECT '0586.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0587.tsv' INTO TABLE bc2pubtator;
SELECT '0587.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0588.tsv' INTO TABLE bc2pubtator;
SELECT '0588.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0589.tsv' INTO TABLE bc2pubtator;
SELECT '0589.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0590.tsv' INTO TABLE bc2pubtator;
SELECT '0590.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0591.tsv' INTO TABLE bc2pubtator;
SELECT '0591.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0592.tsv' INTO TABLE bc2pubtator;
SELECT '0592.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0593.tsv' INTO TABLE bc2pubtator;
SELECT '0593.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0594.tsv' INTO TABLE bc2pubtator;
SELECT '0594.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0595.tsv' INTO TABLE bc2pubtator;
SELECT '0595.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0596.tsv' INTO TABLE bc2pubtator;
SELECT '0596.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0597.tsv' INTO TABLE bc2pubtator;
SELECT '0597.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0598.tsv' INTO TABLE bc2pubtator;
SELECT '0598.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0599.tsv' INTO TABLE bc2pubtator;
SELECT '0599.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0600.tsv' INTO TABLE bc2pubtator;
SELECT '0600.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0601.tsv' INTO TABLE bc2pubtator;
SELECT '0601.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0602.tsv' INTO TABLE bc2pubtator;
SELECT '0602.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0603.tsv' INTO TABLE bc2pubtator;
SELECT '0603.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0604.tsv' INTO TABLE bc2pubtator;
SELECT '0604.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0605.tsv' INTO TABLE bc2pubtator;
SELECT '0605.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0606.tsv' INTO TABLE bc2pubtator;
SELECT '0606.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0607.tsv' INTO TABLE bc2pubtator;
SELECT '0607.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0608.tsv' INTO TABLE bc2pubtator;
SELECT '0608.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0609.tsv' INTO TABLE bc2pubtator;
SELECT '0609.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0610.tsv' INTO TABLE bc2pubtator;
SELECT '0610.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0611.tsv' INTO TABLE bc2pubtator;
SELECT '0611.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0612.tsv' INTO TABLE bc2pubtator;
SELECT '0612.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0613.tsv' INTO TABLE bc2pubtator;
SELECT '0613.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0614.tsv' INTO TABLE bc2pubtator;
SELECT '0614.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0615.tsv' INTO TABLE bc2pubtator;
SELECT '0615.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0616.tsv' INTO TABLE bc2pubtator;
SELECT '0616.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0617.tsv' INTO TABLE bc2pubtator;
SELECT '0617.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0618.tsv' INTO TABLE bc2pubtator;
SELECT '0618.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0619.tsv' INTO TABLE bc2pubtator;
SELECT '0619.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0620.tsv' INTO TABLE bc2pubtator;
SELECT '0620.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0621.tsv' INTO TABLE bc2pubtator;
SELECT '0621.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0622.tsv' INTO TABLE bc2pubtator;
SELECT '0622.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0623.tsv' INTO TABLE bc2pubtator;
SELECT '0623.tsv', CURRENT_DATE(), CURRENT_TIME();
LOAD DATA LOCAL INFILE '/var/lib/mysql/load_files/0624.tsv' INTO TABLE bc2pubtator;
SELECT '0624.tsv', CURRENT_DATE(), CURRENT_TIME();
SELECT 'update auto increment', CURRENT_DATE(), CURRENT_TIME();
ALTER TABLE bc2pubtator AUTO_INCREMENT=385837999;
